api:
  broker:
    exchange:
      userevent: campus.userevent
  url:
    course: http://api-course/api-course/
logging:
  level:
    apiauthuser: TRACE
    org:
      hibernate: INFO
      springframework:
        web: DEBUG
    root: INFO
server:
  port: 8087
  servlet:
    context-path: /api-authuser/
spring:
  application:
    name: api-authuser
  datasource:
    password: 1234512345
    url: jdbc:postgresql://localhost:5432/authuser
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    addresses: amqps://kozkstqk:ctW6Ya10zT9Jy0w0l_tO6zTq21reVths@moose.rmq.cloudamqp.com/kozkstqk

resilience4j:
 retry:
    instances:
      retryInstance:
        maxRetryAttempts: 3
        waitDuration: 5s
 circuitbreaker:
    instances:
      circuitbreakerInstance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80

authuser:
  refreshscope:
    name: Testando o refreshscope.

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
