api:
  broker:
    exchange:
      usereventexchange: campus.userevent
      notificationCommandExchange: api.notificationcommand 
    queue:
      usereventqueue:
        name: campus.userevent.ms.course
    key:
      notificationCommandKey: ms.notification
  url:
    authuser: http://api-authuser/api-authuser/

server:
  port: 8082
  servlet:
    context-path: /api-course/
spring:
  application:
    name: api-course
  datasource:
    password: 1234512345
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    addresses: amqps://kozkstqk:ctW6Ya10zT9Jy0w0l_tO6zTq21reVths@moose.rmq.cloudamqp.com/kozkstqk

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
