server:
  port: 8086
  servlet:
    context-path: /api-payment/

spring:
  application:
    name: api-payment
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: 1234512345
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    addresses: amqps://kozkstqk:ctW6Ya10zT9Jy0w0l_tO6zTq21reVths@moose.rmq.cloudamqp.com/kozkstqk
 
api:
  broker:
    exchange:
      userEventExchange: campus.userevent
    queue:
      userEventQueue:
        name: campus.userevent.ms.payment

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
