server:
  port: 8084
  servlet:
    context-path: '/api-notification/'

spring:
  application:
    name: api-notification
  datasource:
    url:  jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: 1234512345
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: amqps://kozkstqk:ctW6Ya10zT9Jy0w0l_tO6zTq21reVths@moose.rmq.cloudamqp.com/kozkstqk

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

api:
  broker:
    exchange:
      notificationCommandExchange: api.notificationcommand
    queue:
      notificationCommandQueue:
        name: api.notificationcommand.ms.notification
    key:
      notificationCommandKey: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

