api:
  serviceRegistry:
    username: serviceregistry
    password: '123sr'
  auth:
    jwtSecret: p2s5v8y/A?D(G+KbPeShVmYq3t6w9z$C&F)H@McQfTjWnZr4u7x!A%D*G-KaNdRg
    jwtExpirationMs: 14400000

eureka:
  client:
    service-url:
      defaultZone: http://${api.serviceRegistry.username}:${api.serviceRegistry.password}@localhost:8761/eureka
  instance:
    hostname: localhost
    