api:
  serviceRegistry:
    username: serviceregistry
    password: '123sr'

eureka:
  client:
    service-url:
      defaultZone: http://${api.serviceRegistry.username}:${api.serviceRegistry.password}@localhost:8761/eureka
  instance:
    hostname: localhost
    